package G8;

import org.apache.lucene.analysis.*;
import org.apache.lucene.analysis.en.PorterStemFilter;
import org.apache.lucene.analysis.standard.StandardTokenizer;
import org.apache.lucene.analysis.synonym.SolrSynonymParser;
import org.apache.lucene.analysis.synonym.SynonymGraphFilter;
import org.apache.lucene.analysis.synonym.SynonymMap;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;

public class CustomAnalyzer extends Analyzer {
    @Override
    protected TokenStreamComponents createComponents(String s) {

        SynonymMap synonymMap = null;
        try {
            synonymMap = CreateSynonymMap.create();
        } catch (Exception e) {
            e.printStackTrace();
        }
        StandardTokenizer src = new StandardTokenizer();
//        Tokenizer src = new LetterTokenizer();
//        EdgeNGramTokenizer src2 = new EdgeNGramTokenizer();

        TokenStream result = new LowerCaseFilter(src);
        if (synonymMap != null) {
            result = new SynonymGraphFilter(result, synonymMap, true);
        }
        result = new StopFilter(result, getStopWords());
//        result = new EdgeNGramTokenFilter(result, 1, 2, true);
        result = new PorterStemFilter(result);
//        EdgeNGramTokenFilter gramTokenizer = new NGramTokenizer(s, 1, 3);

//        result = new MorfologikFilter(result);
        return new TokenStreamComponents(src, result);
    }

    private static CharArraySet getStopWords() {
        CharArraySet stopWords = new CharArraySet(0, true);
        stopWords.add("no");
        stopWords.add("not");
        stopWords.add("will");
        stopWords.add("a");
        stopWords.add("about");
        stopWords.add("above");
        stopWords.add("after");
        stopWords.add("again");
        stopWords.add("against");
        stopWords.add("all");
        stopWords.add("am");
        stopWords.add("an");
        stopWords.add("and");
        stopWords.add("any");
        stopWords.add("are");
        stopWords.add("as");
        stopWords.add("at");
        stopWords.add("be");
        stopWords.add("because");
        stopWords.add("been");
        stopWords.add("before");
        stopWords.add("being");
        stopWords.add("below");
        stopWords.add("between");
        stopWords.add("both");
        stopWords.add("but");
        stopWords.add("by");
        stopWords.add("could");
        stopWords.add("did");
        stopWords.add("do");
        stopWords.add("does");
        stopWords.add("doing");
        stopWords.add("down");
        stopWords.add("during");
        stopWords.add("each");
        stopWords.add("few");
        stopWords.add("for");
        stopWords.add("from");
        stopWords.add("further");
        stopWords.add("had");
        stopWords.add("has");
        stopWords.add("have");
        stopWords.add("having");
        stopWords.add("he");
//        stopWords.add("he'd");
//        stopWords.add("he'll");
//        stopWords.add("he's");
        stopWords.add("her");
        stopWords.add("here");
//        stopWords.add("here's");
        stopWords.add("hers");
        stopWords.add("herself");
        stopWords.add("him");
        stopWords.add("himself");
        stopWords.add("his");
        stopWords.add("how");
//        stopWords.add("how's");
        stopWords.add("i");
//        stopWords.add("i'd");
//        stopWords.add("i'll");
//        stopWords.add("i'm");
//        stopWords.add("i've");
        stopWords.add("if");
        stopWords.add("in");
        stopWords.add("into");
        stopWords.add("is");
        stopWords.add("it");
//        stopWords.add("it's");
        stopWords.add("its");
        stopWords.add("itself");
//        stopWords.add("let's");
        stopWords.add("me");
        stopWords.add("more");
        stopWords.add("most");
        stopWords.add("my");
        stopWords.add("myself");
        stopWords.add("nor");
        stopWords.add("of");
        stopWords.add("on");
        stopWords.add("once");
        stopWords.add("only");
        stopWords.add("or");
        stopWords.add("other");
        stopWords.add("ought");
        stopWords.add("our");
        stopWords.add("ours");
        stopWords.add("ourselves");
        stopWords.add("out");
        stopWords.add("over");
        stopWords.add("own");
        stopWords.add("same");
        stopWords.add("she");
//        stopWords.add("she'd");
//        stopWords.add("she'll");
//        stopWords.add("she's");
        stopWords.add("should");
        stopWords.add("so");
        stopWords.add("some");
        stopWords.add("such");
        stopWords.add("than");
        stopWords.add("that");
//        stopWords.add("that's");
        stopWords.add("the");
        stopWords.add("their");
        stopWords.add("theirs");
        stopWords.add("them");
        stopWords.add("themselves");
        stopWords.add("then");
        stopWords.add("there");
//        stopWords.add("there's");
        stopWords.add("these");
        stopWords.add("they");
//        stopWords.add("they'd");
//        stopWords.add("they'll");
//        stopWords.add("they're");
//        stopWords.add("they've");
        stopWords.add("this");
        stopWords.add("those");
        stopWords.add("through");
        stopWords.add("to");
        stopWords.add("too");
        stopWords.add("under");
        stopWords.add("until");
        stopWords.add("up");
        stopWords.add("very");
        stopWords.add("was");
        stopWords.add("we");
//        stopWords.add("we'd");
//        stopWords.add("we'll");
//        stopWords.add("we're");
//        stopWords.add("we've");
        stopWords.add("were");
        stopWords.add("what");
//        stopWords.add("what's");
        stopWords.add("when");
//        stopWords.add("when's");
        stopWords.add("where");
//        stopWords.add("where's");
        stopWords.add("which");
        stopWords.add("while");
        stopWords.add("who");
//        stopWords.add("who's");
        stopWords.add("whom");
        stopWords.add("why");
//        stopWords.add("why's");
        stopWords.add("with");
        stopWords.add("would");
        stopWords.add("you");
//        stopWords.add("you'd");
//        stopWords.add("you'll");
//        stopWords.add("you're");
//        stopWords.add("you've");
        stopWords.add("your");
        stopWords.add("yours");
        stopWords.add("yourself");
        stopWords.add("yourselves");
        stopWords.add("used");
        stopWords.add("ae.");
        stopWords.add("may");
        stopWords.add("also");
        stopWords.add("given");
        stopWords.add("hed");
        stopWords.add("hell");
        stopWords.add("hes");
        stopWords.add("heres");
        stopWords.add("hows");
        stopWords.add("id");
        stopWords.add("ill");
        stopWords.add("im");
        stopWords.add("ive");
        stopWords.add("its");
        stopWords.add("lets");
        stopWords.add("shed");
        stopWords.add("shell");
        stopWords.add("shes");
        stopWords.add("thats");
        stopWords.add("theres");
        stopWords.add("theyd");
        stopWords.add("theyll");
        stopWords.add("theyre");
        stopWords.add("theyve");
        stopWords.add("wed");
        stopWords.add("well");
        stopWords.add("were");
        stopWords.add("weve");
        stopWords.add("whats");
        stopWords.add("whens");
        stopWords.add("wheres");
        stopWords.add("whos");
        stopWords.add("whys");
        stopWords.add("youd");
        stopWords.add("youll");
        stopWords.add("youre");
        stopWords.add("youve");

        return stopWords;
    }
}
